# fly.toml app configuration file generated for pv-smp-js on 2023-11-20T03:20:56-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pv-smp-js"
primary_region = "gig"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
